services:
  crypto_pipeline:
    build: .
    container_name: crypto_project
    volumes:
      - .:/app
    environment:
    - API_PORT=${API_PORT}
    - PYTHONUNBUFFERED=1
    ports:
     - "8000:${API_PORT}" 